version: '3.8'
services:
  nli:
    build:
      context: "../"
      dockerfile: "Docker/Dockerfile"
    container_name: 'hol-ccg'
    restart: always
    tty: true
    volumes:
      - type: bind
        source: "../"
        target: "/code"
    environment:
      - PYTHONUNBUFFERED=0
      - PYTHONPATH=/code
    working_dir: '/code'
    shm_size: '2gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']
              count: 2
              capabilities: [gpu]
